### ISSUE TITLE
Kr5ddit.com is down

### ISSUE THREAD

**Issue by orionblastar** [procrasti/K666#6]
I hope you are working on something and took the server down to fix something and will put it back up later.

I think we finally taught TDillo the value of a Kr5ddit, he now knows I sold most of my Kr5ddits for Bitcons, and that Kr5ddits can be used to mod down or up any post or comment. Maybe he'll quit with the fake user sock puppets and anonymous trolls and just post as himself?

**Comment by procrasti** [comment]
It's up now!
